export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_EMPLOYEE_BY_ID_SUCCESS = 'LOAD_EMPLOYEE_BY_ID_SUCCESS';
export const LOAD_TITLES_SUCCESS = 'LOAD_TITLES_SUCCESS';
export const LOAD_EXPERIENCES_SUCCESS = 'LOAD_EXPERIENCES_SUCCESS';
export const LOAD_COMPETENTLEVELS_SUCCESS = 'LOAD_COMPETENTLEVELS_SUCCESS';
export const LOAD_SKILLCATEGORIES_SUCCESS = 'LOAD_SKILLCATEGORIES_SUCCESS';
export const UPDATE_EMPLOYEE_SUCCESS = 'UPDATE_EMPLOYEE_SUCCESS';

// project action type 
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const ENTER_TO_PROJECT_DETAIL = 'ENTER_TO_PROJECT_DETAIL';
export const LOAD_PROJECTS_DETAIL = 'LOAD_PROJECTS_DETAIL';