export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_TITLES_SUCCESS = 'LOAD_TITLES_SUCCESS';

// project action type 
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';