export const LOAD_EMPLOYEES_SUCCESS = 'LOAD_EMPLOYEES_SUCCESS';
export const LOAD_TITLES_SUCCESS = 'LOAD_TITLES_SUCCESS';

// project action type 
export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const ENTER_TO_PROJECT_DETAIL = 'ENTER_TO_PROJECT_DETAIL';
export const LOAD_PROJECTS_DETAIL = 'LOAD_PROJECTS_DETAIL';